<?php

// Mock apartment & condo data for Bangkok
// This file is used for demo / prototyping without a real database.

if (!isset($mockApartments)) {
    $mockApartments = [
        [
            'id' => 1,
            'name' => 'Skyline Residence Rama 9',
            'type' => 'condo',
            'rental_type' => ['monthly'],
            'district' => 'ห้วยขวาง',
            'province' => 'กรุงเทพมหานคร',
            'price_monthly' => 12000,
            'price_daily' => null,
            'is_popular' => true,
            'rating' => 4.7,
            'amenities' => ['WiFi', 'ที่จอดรถ', 'ฟิตเนส', 'สระว่ายน้ำ'],
            'pet_friendly' => false,
            'categories' => ['near_transit', 'near_mall'],
            'thumbnail' => 'https://images.unsplash.com/photo-1664372623516-0b1540d6771e?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'description' => 'คอนโดโลว์ไรซ์ใกล้ MRT พระราม 9 เดินทางสะดวก พร้อมส่วนกลางครบครัน',
            'views' => 1540,
            'max_occupancy' => 2,
            'featured_monthly' => true,
            'featured_daily' => false,
        ],
        [
            'id' => 2,
            'name' => 'Chao Phraya Riverside Apartment',
            'type' => 'apartment',
            'rental_type' => ['daily', 'monthly'],
            'district' => 'คลองสาน',
            'province' => 'กรุงเทพมหานคร',
            'price_monthly' => 18000,
            'price_daily' => 1200,
            'is_popular' => true,
            'rating' => 4.8,
            'amenities' => ['WiFi', 'วิวแม่น้ำ', 'ฟิตเนส', 'สระว่ายน้ำ'],
            'pet_friendly' => true,
            'categories' => ['luxury', 'pet_friendly'],
            'thumbnail' => 'https://images.unsplash.com/photo-1632743441209-8a09b8a37e25?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'description' => 'อพาร์ตเม้นริมน้ำเจ้าพระยา เหมาะสำหรับทั้งอยู่รายวันและรายเดือน',
            'views' => 2100,
            'max_occupancy' => 3,
            'featured_monthly' => true,
            'featured_daily' => true,
        ],
        [
            'id' => 3,
            'name' => 'Green Garden Apartment Ladprao',
            'type' => 'apartment',
            'rental_type' => ['monthly'],
            'district' => 'ลาดพร้าว',
            'province' => 'กรุงเทพมหานคร',
            'price_monthly' => 7500,
            'price_daily' => null,
            'is_popular' => true,
            'rating' => 4.5,
            'amenities' => ['WiFi', 'ที่จอดรถ', 'กล้องวงจรปิด'],
            'pet_friendly' => true,
            'categories' => ['pet_friendly', 'near_park'],
            'thumbnail' => 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop',
            'description' => 'อพาร์ตเม้นท์สีเขียว บรรยากาศสงบ เป็นส่วนตัว ใกล้แหล่งของกินลาดพร้าว',
            'views' => 1320,
            'max_occupancy' => 2,
            'featured_monthly' => true,
            'featured_daily' => false,
        ],
        [
            'id' => 4,
            'name' => 'Sukhumvit 11 Boutique Condo',
            'type' => 'condo',
            'rental_type' => ['daily'],
            'district' => 'วัฒนา',
            'province' => 'กรุงเทพมหานคร',
            'price_monthly' => null,
            'price_daily' => 1900,
            'is_popular' => true,
            'rating' => 4.9,
            'amenities' => ['WiFi', 'ฟิตเนส', 'สระว่ายน้ำ', 'รูมเซอร์วิส'],
            'pet_friendly' => false,
            'categories' => ['luxury', 'near_transit'],
            'thumbnail' => 'https://images.unsplash.com/photo-1630699144057-7d5249ef4e6a?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'description' => 'คอนโดหรูใจกลางสุขุมวิท เหมาะสำหรับสายท่องราตรีและทำงานในเมือง',
            'views' => 2650,
            'max_occupancy' => 2,
            'featured_monthly' => false,
            'featured_daily' => true,
        ],
        [
            'id' => 5,
            'name' => 'Old Town Cozy Loft',
            'type' => 'apartment',
            'rental_type' => ['daily', 'monthly'],
            'district' => 'พระนคร',
            'province' => 'กรุงเทพมหานคร',
            'price_monthly' => 14500,
            'price_daily' => 1500,
            'is_popular' => true,
            'rating' => 4.6,
            'amenities' => ['WiFi', 'ครัว', 'ใกล้สถานที่ท่องเที่ยว'],
            'pet_friendly' => false,
            'categories' => [],
            'thumbnail' => 'https://images.unsplash.com/photo-1444418776041-9c7e33cc5a9c?w=600&h=400&fit=crop',
            'description' => 'ลอฟต์สุดชิคในย่านเมืองเก่า ใกล้วัดพระแก้วและถนนข้าวสาร',
            'views' => 1890,
            'max_occupancy' => 3,
            'featured_monthly' => false,
            'featured_daily' => true,
        ],
        [
            'id' => 6,
            'name' => 'Ratchada City View',
            'type' => 'condo',
            'rental_type' => ['monthly'],
            'district' => 'ดินแดง',
            'province' => 'กรุงเทพมหานคร',
            'price_monthly' => 9000,
            'price_daily' => null,
            'is_popular' => false,
            'rating' => 4.3,
            'amenities' => ['WiFi', 'ฟิตเนส', 'ที่จอดรถ'],
            'pet_friendly' => false,
            'categories' => ['near_transit'],
            'thumbnail' => 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&h=400&fit=crop',
            'description' => 'คอนโดย่านรัชดา วิวเมือง เดินทางสะดวกทั้งรถไฟฟ้าและรถส่วนตัว',
            'views' => 870,
            'max_occupancy' => 2,
            'featured_monthly' => true,
            'featured_daily' => false,
        ],
        [
            'id' => 7,
            'name' => 'Thonglor Pet-Friendly Residence',
            'type' => 'apartment',
            'rental_type' => ['monthly'],
            'district' => 'วัฒนา',
            'province' => 'กรุงเทพมหานคร',
            'price_monthly' => 22000,
            'price_daily' => null,
            'is_popular' => true,
            'rating' => 4.9,
            'amenities' => ['WiFi', 'ที่จอดรถ', 'ฟิตเนส', 'เลี้ยงสัตว์ได้'],
            'pet_friendly' => true,
            'categories' => ['luxury', 'pet_friendly'],
            'thumbnail' => 'https://plus.unsplash.com/premium_photo-1684175656320-5c3f701c082c?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'description' => 'อพาร์ตเม้นท์หรูใจกลางทองหล่อ รองรับสัตว์เลี้ยง พร้อมพื้นที่สวนส่วนกลาง',
            'views' => 3100,
            'max_occupancy' => 4,
            'featured_monthly' => true,
            'featured_daily' => false,
        ],
        [
            'id' => 8,
            'name' => 'Bangna Budget Apartment',
            'type' => 'apartment',
            'rental_type' => ['monthly'],
            'district' => 'บางนา',
            'province' => 'กรุงเทพมหานคร',
            'price_monthly' => 5500,
            'price_daily' => null,
            'is_popular' => false,
            'rating' => 4.1,
            'amenities' => ['WiFi', 'ที่จอดรถ'],
            'pet_friendly' => false,
            'categories' => [],
            'thumbnail' => 'https://images.unsplash.com/photo-1560448204-61dc36dc98c8?w=600&h=400&fit=crop',
            'description' => 'ห้องพักราคาประหยัด เหมาะสำหรับพนักงานออฟฟิศย่านบางนา-ศรีนครินทร์',
            'views' => 640,
            'max_occupancy' => 1,
            'featured_monthly' => false,
            'featured_daily' => false,
        ],
        [
            'id' => 9,
            'name' => 'Ari Minimal Loft',
            'type' => 'apartment',
            'rental_type' => ['daily', 'monthly'],
            'district' => 'พญาไท',
            'province' => 'กรุงเทพมหานคร',
            'price_monthly' => 16000,
            'price_daily' => 1700,
            'is_popular' => true,
            'rating' => 4.7,
            'amenities' => ['WiFi', 'คาเฟ่ชั้นล่าง', 'ที่จอดรถ'],
            'pet_friendly' => false,
            'categories' => [],
            'thumbnail' => 'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=600&h=400&fit=crop',
            'description' => 'ลอฟต์สไตล์มินิมอลในย่านอารีย์ ใกล้ร้านกาแฟและร้านอาหารชื่อดัง',
            'views' => 1750,
            'max_occupancy' => 2,
            'featured_monthly' => true,
            'featured_daily' => true,
        ],
        [
            'id' => 10,
            'name' => 'Silom Business Suite',
            'type' => 'condo',
            'rental_type' => ['daily'],
            'district' => 'บางรัก',
            'province' => 'กรุงเทพมหานคร',
            'price_monthly' => null,
            'price_daily' => 2200,
            'is_popular' => true,
            'rating' => 4.8,
            'amenities' => ['WiFi', 'ฟิตเนส', 'สระว่ายน้ำ', 'ห้องประชุม'],
            'pet_friendly' => false,
            'categories' => ['luxury', 'near_transit', 'near_hospital'],
            'thumbnail' => 'https://images.unsplash.com/photo-1649068453220-f7394ee150d1?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
            'description' => 'ห้องพักสำหรับนักธุรกิจ ใกล้ BTS ศาลาแดง และตึกออฟฟิศสำคัญ',
            'views' => 1980,
            'max_occupancy' => 2,
            'featured_monthly' => false,
            'featured_daily' => true,
        ],
        [
            'id' => 11,
            'name' => 'Onnut Cozy Corner',
            'type' => 'apartment',
            'rental_type' => ['monthly'],
            'district' => 'สวนหลวง',
            'province' => 'กรุงเทพมหานคร',
            'price_monthly' => 6800,
            'price_daily' => null,
            'is_popular' => false,
            'rating' => 4.2,
            'amenities' => ['WiFi', 'ใกล้ห้างสรรพสินค้า'],
            'pet_friendly' => true,
            'categories' => ['near_transit', 'near_mall', 'pet_friendly'],
            'thumbnail' => 'https://images.unsplash.com/photo-1484100356142-db6ab6244067?w=600&h=400&fit=crop',
            'description' => 'อพาร์ตเม้นท์โฮมมี่ ใกล้ BTS อ่อนนุช และห้าง Century',
            'views' => 720,
            'max_occupancy' => 2,
            'featured_monthly' => false,
            'featured_daily' => false,
        ],
        [
            'id' => 12,
            'name' => 'Chatuchak Park View Condo',
            'type' => 'condo',
            'rental_type' => ['monthly'],
            'district' => 'จตุจักร',
            'province' => 'กรุงเทพมหานคร',
            'price_monthly' => 13500,
            'price_daily' => null,
            'is_popular' => true,
            'rating' => 4.6,
            'amenities' => ['WiFi', 'สวนส่วนกลาง', 'ที่จอดรถ'],
            'pet_friendly' => false,
            'categories' => ['near_park'],
            'thumbnail' => 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&h=400&fit=crop',
            'description' => 'คอนโดวิวสวนจตุจักร เหมาะสำหรับคนทำงานย่านลาดพร้าว-รัชโยธิน',
            'views' => 1430,
            'max_occupancy' => 3,
            'featured_monthly' => true,
            'featured_daily' => false,
        ],
        [
            'id' => 13,
            'name' => 'Riverside Daily Studio',
            'type' => 'apartment',
            'rental_type' => ['daily'],
            'district' => 'ธนบุรี',
            'province' => 'กรุงเทพมหานคร',
            'price_monthly' => null,
            'price_daily' => 900,
            'is_popular' => false,
            'rating' => 4.3,
            'amenities' => ['WiFi', 'วิวแม่น้ำ'],
            'pet_friendly' => false,
            'categories' => [],
            'thumbnail' => 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=600&h=400&fit=crop',
            'description' => 'สตูดิโอเล็ก ๆ วิวมุมสูงริมฝั่งธน เหมาะสำหรับพักผ่อนระยะสั้น',
            'views' => 540,
            'max_occupancy' => 1,
            'featured_monthly' => false,
            'featured_daily' => true,
        ],
        [
            'id' => 14,
            'name' => 'Bangkok Creative Hub Loft',
            'type' => 'apartment',
            'rental_type' => ['daily', 'monthly'],
            'district' => 'ปทุมวัน',
            'province' => 'กรุงเทพมหานคร',
            'price_monthly' => 20000,
            'price_daily' => 2300,
            'is_popular' => true,
            'rating' => 4.9,
            'amenities' => ['WiFi', 'Co-working space', 'ฟิตเนส'],
            'pet_friendly' => true,
            'categories' => ['luxury', 'pet_friendly', 'near_transit'],
            'thumbnail' => 'https://images.unsplash.com/photo-1484100356142-db6ab6244067?w=600&h=400&fit=crop',
            'description' => 'ลอฟต์สำหรับสายครีเอทีฟ ใกล้ BTS สนามกีฬา และสยามพารากอน',
            'views' => 3200,
            'max_occupancy' => 4,
            'featured_monthly' => true,
            'featured_daily' => true,
        ],
        [
            'id' => 15,
            'name' => 'Lat Krabang Airport Residence',
            'type' => 'apartment',
            'rental_type' => ['daily', 'monthly'],
            'district' => 'ลาดกระบัง',
            'province' => 'กรุงเทพมหานคร',
            'price_monthly' => 6500,
            'price_daily' => 800,
            'is_popular' => false,
            'rating' => 4.2,
            'amenities' => ['WiFi', 'ใกล้สนามบิน', 'ที่จอดรถ'],
            'pet_friendly' => false,
            'categories' => [],
            'thumbnail' => 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=600&h=400&fit=crop',
            'description' => 'อพาร์ตเม้นท์ใกล้สนามบินสุวรรณภูมิ เหมาะสำหรับพนักงานสายการบิน',
            'views' => 910,
            'max_occupancy' => 2,
            'featured_monthly' => false,
            'featured_daily' => true,
        ],
        [
            'id' => 16,
            'name' => 'Sathorn Executive Suite',
            'type' => 'condo',
            'rental_type' => ['monthly'],
            'district' => 'สาทร',
            'province' => 'กรุงเทพมหานคร',
            'price_monthly' => 28000,
            'price_daily' => null,
            'is_popular' => true,
            'rating' => 4.8,
            'amenities' => ['WiFi', 'ฟิตเนส', 'สระว่ายน้ำ', 'ห้องประชุม'],
            'pet_friendly' => false,
            'categories' => ['luxury', 'near_transit', 'near_hospital'],
            'thumbnail' => 'https://images.unsplash.com/photo-1505691723518-36a5ac3be353?w=600&h=400&fit=crop',
            'description' => 'ห้องชุดสำหรับผู้บริหาร ใกล้รถไฟฟ้าและอาคารสำนักงานใหญ่หลายแห่ง',
            'views' => 2500,
            'max_occupancy' => 3,
            'featured_monthly' => true,
            'featured_daily' => false,
        ],
        [
            'id' => 17,
            'name' => 'Ramkhamhaeng Student Home',
            'type' => 'apartment',
            'rental_type' => ['monthly'],
            'district' => 'บางกะปิ',
            'province' => 'กรุงเทพมหานคร',
            'price_monthly' => 5500,
            'price_daily' => null,
            'is_popular' => true,
            'rating' => 4.0,
            'amenities' => ['WiFi', 'เครื่องซักผ้าหยอดเหรียญ', 'ใกล้มหาวิทยาลัย'],
            'pet_friendly' => false,
            'categories' => ['near_school', 'near_university'],
            'thumbnail' => 'https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=600&h=400&fit=crop',
            'description' => 'หอพักนักศึกษาใกล้ม.รามคำแหง เดินทางสะดวก ราคาย่อมเยา',
            'views' => 1300,
            'max_occupancy' => 1,
            'featured_monthly' => true,
            'featured_daily' => false,
        ],
        [
            'id' => 18,
            'name' => 'Ekkamai Urban Stay',
            'type' => 'apartment',
            'rental_type' => ['daily'],
            'district' => 'วัฒนา',
            'province' => 'กรุงเทพมหานคร',
            'price_monthly' => null,
            'price_daily' => 1600,
            'is_popular' => true,
            'rating' => 4.5,
            'amenities' => ['WiFi', 'Co-working space', 'คาเฟ่'],
            'pet_friendly' => true,
            'categories' => ['pet_friendly', 'near_transit'],
            'thumbnail' => 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop',
            'description' => 'ที่พักสไตล์คนเมืองย่านเอกมัย ใกล้แหล่งแฮงเอาท์และร้านกาแฟ',
            'views' => 1900,
            'max_occupancy' => 2,
            'featured_monthly' => false,
            'featured_daily' => true,
        ],
        [
            'id' => 19,
            'name' => 'Victory Monument Transit Condo',
            'type' => 'condo',
            'rental_type' => ['monthly'],
            'district' => 'พญาไท',
            'province' => 'กรุงเทพมหานคร',
            'price_monthly' => 11000,
            'price_daily' => null,
            'is_popular' => false,
            'rating' => 4.4,
            'amenities' => ['WiFi', 'ที่จอดรถ', 'ฟิตเนส'],
            'pet_friendly' => false,
            'categories' => ['near_transit'],
            'thumbnail' => 'https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=600&h=400&fit=crop',
            'description' => 'คอนโดย่านอนุสาวรีย์ฯ เหมาะกับคนทำงานที่ต้องเดินทางหลายเส้นทาง',
            'views' => 980,
            'max_occupancy' => 2,
            'featured_monthly' => true,
            'featured_daily' => false,
        ],
        [
            'id' => 20,
            'name' => 'Bangkok Old Quarter Stay',
            'type' => 'apartment',
            'rental_type' => ['daily'],
            'district' => 'พระนคร',
            'province' => 'กรุงเทพมหานคร',
            'price_monthly' => null,
            'price_daily' => 1300,
            'is_popular' => false,
            'rating' => 4.3,
            'amenities' => ['WiFi', 'ใกล้สถานที่ท่องเที่ยว', 'ครัว'],
            'pet_friendly' => false,
            'categories' => [],
            'thumbnail' => 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=600&h=400&fit=crop',
            'description' => 'อพาร์ตเม้นท์สไตล์วินเทจในย่านเมืองเก่า เหมาะสำหรับสายเที่ยววัด-คาเฟ่',
            'views' => 860,
            'max_occupancy' => 2,
            'featured_monthly' => false,
            'featured_daily' => true,
        ],
    ];
}

if (!function_exists('mock_get_all_apartments')) {
    function mock_get_all_apartments(): array
    {
        global $mockApartments;
        return $mockApartments;
    }
}

if (!function_exists('mock_get_popular_apartments')) {
    function mock_get_popular_apartments(int $limit = 5): array
    {
        $items = array_filter(mock_get_all_apartments(), function ($apt) {
            return !empty($apt['is_popular']);
        });

        usort($items, function ($a, $b) {
            return ($b['views'] <=> $a['views']) ?: ($b['rating'] <=> $a['rating']);
        });

        return array_slice($items, 0, $limit);
    }
}

if (!function_exists('mock_get_monthly_apartments')) {
    function mock_get_monthly_apartments(int $limit = 5): array
    {
        $items = array_filter(mock_get_all_apartments(), function ($apt) {
            $hasMonthly = in_array('monthly', $apt['rental_type'], true) || !empty($apt['price_monthly']);
            return $hasMonthly;
        });

        usort($items, function ($a, $b) {
            return ($b['featured_monthly'] <=> $a['featured_monthly'])
                ?: ($b['rating'] <=> $a['rating']);
        });

        return array_slice($items, 0, $limit);
    }
}

if (!function_exists('mock_get_daily_apartments')) {
    function mock_get_daily_apartments(int $limit = 5): array
    {
        $items = array_filter(mock_get_all_apartments(), function ($apt) {
            $hasDaily = in_array('daily', $apt['rental_type'], true) || !empty($apt['price_daily']);
            return $hasDaily;
        });

        usort($items, function ($a, $b) {
            return ($b['featured_daily'] <=> $a['featured_daily'])
                ?: ($b['rating'] <=> $a['rating']);
        });

        return array_slice($items, 0, $limit);
    }
}
